# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChineseFoodRank', '0041_delete_commodity'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
