# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChineseFoodRank', '0044_auto_20160321_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodstyle',
            name='style',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
