# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChineseFoodRank', '0046_auto_20160321_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='style',
        ),
        migrations.DeleteModel(
            name='Category2',
        ),
    ]
