# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChineseFoodRank', '0047_auto_20160321_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
