# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChineseFoodRank', '0052_category1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category1',
        ),
    ]
