# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChineseFoodRank', '0056_food_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='food',
            name='views',
        ),
    ]
