# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChineseFoodRank', '0057_auto_20160321_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ChineseFoodRank.Category'),
        ),
        migrations.AlterField(
            model_name='food',
            name='style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ChineseFoodRank.Style'),
        ),
        migrations.AlterField(
            model_name='food',
            name='title',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
