# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChineseFoodRank', '0058_auto_20160322_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
