# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChineseFoodRank', '0059_remove_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
