# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChineseFoodRank', '0060_food_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='slug',
        ),
    ]
