# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 00:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChineseFoodRank', '0062_auto_20160322_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='link',
        ),
        migrations.AddField(
            model_name='vote',
            name='food',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ChineseFoodRank.Food'),
            preserve_default=False,
        ),
    ]
